site_name: ADToolbox

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


theme:
  name: "material"

nav:
  - index.md
  - Installation: Installation.md
  - Commandline Interface: CLI.md
  - API: API.md
  - Parameter Tuning: Parameter_Tuning.md

plugins:
  - mkdocstrings