site_name: ADToolbox




theme:
  name: "material"

nav:
  - index.md
  - Installation: Installation.md
  - Commandline Interface: CLI.md
  - API: API.md
  - Modeling Pipeline: modeling.html
  - Parameter Tuning Pipeline: parameter_tuning.html
  - Metagenomics Pipelines: Metagenomics_Pipeline.md

plugins:
  - mkdocstrings